apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" .Chart.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: "{{ $v }}"
{{- end }}
