apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable | quote }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge | quote }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ printf "%s-%s" .Chart.Name .Values.serviceAccountName }}
{{- if gt (len .Values.nodeAffinity.values) 0 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeAffinity.key }}
                    operator: In
                    values:
{{- range .Values.nodeAffinity.values }}
                      - "{{ . }}"
{{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
{{- range $k, $v := .Values.secrets }}
            - name: "{{ $k }}"
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-secrets" $.Chart.Name }}
                  key: "{{ $k }}"
{{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s-pvc" .Chart.Name }}
