apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" .Chart.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
